steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/gke-llm/mamba3-tpu:latest'
      - '-f'
      - 'mamba_tpu/Dockerfile'
      - '.'

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/gke-llm/mamba3-tpu:latest'

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/gke-llm/mamba3-tpu:latest'

timeout: "14400s" # 4 hours
options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: 200
