apiVersion: v1
kind: Pod
metadata:
  name: gcs-uploader
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  restartPolicy: Never
  serviceAccountName: gcs-sa
  containers:
  - name: uploader
    image: ubuntu:latest
    command: ["sleep", "3600"]
    volumeMounts:
    - name: gcs-fuse-writing
      mountPath: /gcs-fuse
  volumes:
  - name: gcs-fuse-writing
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: rick-tpu7x
        mountOptions: "only-dir=torch-tpu,implicit-dirs"
